/* Generated By:JJTree: Do not edit this line. ASTForall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qpar.master.logic.parser;

public
class ASTForall extends SimpleNode {
  public ASTForall(int id) {
    super(id);
  }

  public ASTForall(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a4ead07c025819cf719443e54a26f1a (do not edit this line) */
