/* Generated By:JJTree: Do not edit this line. ASTQuantifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qpar.master.logic.parser;

public
class ASTQuantifier extends SimpleNode {
  public ASTQuantifier(int id) {
    super(id);
  }

  public ASTQuantifier(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72cc9bc117271a2f70e070bda990f5ac (do not edit this line) */
