/* Generated By:JJTree: Do not edit this line. ASTOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qpar.common.parser.jjtree;

public class ASTOr extends SimpleNode {
	public ASTOr(int id) {
		super(id);
	}

	public ASTOr(Qbf_parser p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=67022cb141bc99801642e527f1867fa8 (do not edit this
 * line)
 */
