/* Generated By:JavaCC: Do not edit this line. Qbf_parserVisitor.java Version 4.1d1 */
package qpar.common.parser.jjtree;

public interface Qbf_parserVisitor {
	public Object visit(SimpleNode node, Object data);
}
/*
 * JavaCC - OriginalChecksum=5a5953d4c3e20954b20de052eafa8bb4 (do not edit this
 * line)
 */
