/* Generated By:JavaCC: Do not edit this line. Qbf_parserTreeConstants.java Version 5.0 */
package qpar.common.parser.jjtree;

public interface Qbf_parserTreeConstants {
	public int JJTINPUT = 0;
	public int JJTAND = 1;
	public int JJTOR = 2;
	public int JJTVOID = 3;
	public int JJTVAR = 4;
	public int JJTLOGICAL = 5;
	public int JJTQUANTIFIER = 6;

	public String[] jjtNodeName = { "Input", "And", "Or", "void", "Var", "Logical", "Quantifier", };
}
/*
 * JavaCC - OriginalChecksum=9898f1ef033b143fd3194d83f8262a25 (do not edit this
 * line)
 */
