/* Generated By:JJTree: Do not edit this line. ASTLogical.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qpar.common.parser;

public class ASTLogical extends SimpleNode {
	public ASTLogical(int id) {
		super(id);
	}

	public ASTLogical(Qbf_parser p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=a653a4ecc7e346660ac2f0b854933749 (do not edit this
 * line)
 */
