/* Generated By:JJTree: Do not edit this line. ASTExists.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.logic.parser;

public
class ASTExists extends SimpleNode {
  public ASTExists(int id) {
    super(id);
  }

  public ASTExists(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a8365691d6fac51898b9ed2a73facd9 (do not edit this line) */
