/* Generated By:JJTree: Do not edit this line. ASTExists.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTExists extends SimpleNode {
  public ASTExists(int id) {
    super(id);
  }

  public ASTExists(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dbee8fbb2b64f53d4dc770edb6736286 (do not edit this line) */
