/* Generated By:JJTree: Do not edit this line. ASTForall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTForall extends SimpleNode {
  public ASTForall(int id) {
    super(id);
  }

  public ASTForall(Qbf_parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Qbf_parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=940026ca0f11b7390216d81dd829630d (do not edit this line) */
