/* Generated By:JJTree: Do not edit this line. ASTForall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTForall extends SimpleNode {
  public ASTForall(int id) {
    super(id);
  }

  public ASTForall(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f78dd37f3985d98c81cfcbaa08b5dfa (do not edit this line) */
