/* Generated By:JJTree: Do not edit this line. ASTLp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTLp extends SimpleNode {
  public ASTLp(int id) {
    super(id);
  }

  public ASTLp(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70d85d4059a2b0aecbc85bad31fe87c2 (do not edit this line) */
