/* Generated By:JJTree: Do not edit this line. ASTLogical.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTLogical extends SimpleNode {
  public ASTLogical(int id) {
    super(id);
  }

  public ASTLogical(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=846dc0c37b44a263ff85c88a69f7d6a3 (do not edit this line) */
