/* Generated By:JJTree: Do not edit this line. ASTOp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTOp extends SimpleNode {
  public ASTOp(int id) {
    super(id);
  }

  public ASTOp(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2361c1b768d52d74accf96f58c92d099 (do not edit this line) */
