/* Generated By:JJTree: Do not edit this line. ASTOpNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTOpNode extends SimpleNode {
  public ASTOpNode(int id) {
    super(id);
  }

  public ASTOpNode(Qbf_parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Qbf_parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bcee3d8c51f7e0163c5ea524ac75026f (do not edit this line) */
