/* Generated By:JJTree: Do not edit this line. ASTQuant.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTQuant extends SimpleNode {
  public ASTQuant(int id) {
    super(id);
  }

  public ASTQuant(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9bb31677f21ba9c600233dd83df791aa (do not edit this line) */
