/* Generated By:JJTree: Do not edit this line. ASTQ_set.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTQ_set extends SimpleNode {
  public ASTQ_set(int id) {
    super(id);
  }

  public ASTQ_set(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=300b3bc61eda551ee01ab1a16a8616af (do not edit this line) */
