/* Generated By:JJTree: Do not edit this line. ASTQuant.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTQuant extends SimpleNode {
	private int id;

  public ASTQuant(int id) {
    super(id);
  }

  public ASTQuant(Qbf_parser p, int id) {
    super(p, id);
  }


	public void setId(int id) {
		this.id = id;
	}
	public int getId() {
		return id;
	}
	
  /** Accept the visitor. **/
  public Object jjtAccept(Qbf_parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=271440123e49cb3bec2ade967e81d16d (do not edit this line) */
