/* Generated By:JJTree: Do not edit this line. ASTQuant.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTQuant extends SimpleNode {
  public ASTQuant(int id) {
    super(id);
  }

  public ASTQuant(Qbf_parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Qbf_parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b19f256101f6c8dfe90cfd19344991a5 (do not edit this line) */
