/* Generated By:JJTree: Do not edit this line. ASTVarList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVarList extends SimpleNode {
  public ASTVarList(int id) {
    super(id);
  }

  public ASTVarList(Qbf_parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Qbf_parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=94e48c5a1627f7c0ee9bc4b810bc5e26 (do not edit this line) */
