/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;



public class ASTVar extends SimpleNode {

	

  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50b412799f1d2a58520e31dc9292c8f7 (do not edit this line) */
