/* Generated By:JJTree: Do not edit this line. ASTVar_list.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

public class ASTVar_list extends SimpleNode {
  public ASTVar_list(int id) {
    super(id);
  }

  public ASTVar_list(Qbf_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d12898887299188e46f092bea1f4449 (do not edit this line) */
