/* Generated By:JJTree: Do not edit this line. Node.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package main.java.logic.parser;

/* All AST nodes must implement this interface.  It provides basic
   machinery for constructing the parent and child relationships
   between nodes. */

public interface Node {

	// custom stuff begin
	public String op = "";
	public String truthValue = "";
	public int var = -1;	
	public int id = 0;
	public boolean reducable = false;
	public String traverse();
	public boolean reduce();
	public void assignTruthValue(int v, boolean b);
	public void dump(String prefix);
	public void deleteChildren();
	public String getOp();
	public void setOp(String o);
	public void setTruthValue(String t);
	public String getTruthValue();
	public void setVar(int v);
	public int getVar();
	public boolean replaceChild(Node oldNode, Node newNode);
	public int getId();
	// custon stuff end

  /** This method is called after the node has been made the current
    node.  It indicates that child nodes can now be added to it. */
  public void jjtOpen();

  /** This method is called after all the child nodes have been
    added. */
  public void jjtClose();

  /** This pair of methods are used to inform the node of its
    parent. */
  public void jjtSetParent(Node n);
  public Node jjtGetParent();

  /** This method tells the node to add its argument to the node's
    list of children.  */
  public void jjtAddChild(Node n, int i);

  /** This method returns a child node.  The children are numbered
     from zero, left to right. */
  public Node jjtGetChild(int i);

  /** Return the number of children the node has. */
  public int jjtGetNumChildren();
}
/* JavaCC - OriginalChecksum=da36fe88221b68880cf1dc230284ea8c (do not edit this line) */
