/* Generated By:JavaCC: Do not edit this line. Qbf_parserVisitor.java Version 4.1d1 */
package main.java.logic.parser;

public interface Qbf_parserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTQuant node, Object data);
  public Object visit(ASTOp node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTVar node, Object data);
}
/* JavaCC - OriginalChecksum=bc1474a80e91fdde3020d53b7d246dba (do not edit this line) */
