/* Generated By:JavaCC: Do not edit this line. Qbf_parserTreeConstants.java Version 4.1d1 */
package main.java.logic.parser;

public interface Qbf_parserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTQUANT = 1;
  public int JJTVOID = 2;
  public int JJTAND = 3;
  public int JJTOR = 4;
  public int JJTNOT = 5;
  public int JJTVAR = 6;


  public String[] jjtNodeName = {
    "Start",
    "Quant",
    "void",
    "And",
    "Or",
    "Not",
    "Var",
  };
}
/* JavaCC - OriginalChecksum=251e1c6d53a5b15a352c7a25ccabdb07 (do not edit this line) */
