/* Generated By:JJTree&JavaCC: Do not edit this line. Qbf_parserConstants.java */
package main.java.logic.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Qbf_parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int LP = 8;
  /** RegularExpression Id. */
  int RP = 9;
  /** RegularExpression Id. */
  int LSP = 10;
  /** RegularExpression Id. */
  int RSP = 11;
  /** RegularExpression Id. */
  int EXISTS = 12;
  /** RegularExpression Id. */
  int FORALL = 13;
  /** RegularExpression Id. */
  int VAR = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"exists\"",
    "\"forall\"",
    "<VAR>",
  };

}
