/* Generated By:JavaCC: Do not edit this line. Qbf_parserTreeConstants.java Version 4.1d1 */
public interface Qbf_parserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTQUANT = 1;
  public int JJTOP = 2;
  public int JJTEXPRESSION = 3;
  public int JJTVARLIST = 4;
  public int JJTVOID = 5;


  public String[] jjtNodeName = {
    "Start",
    "Quant",
    "Op",
    "Expression",
    "VarList",
    "void",
  };
}
/* JavaCC - OriginalChecksum=0a2714d67ad38e8f7353ae0908e628ca (do not edit this line) */
