/* Generated By:JavaCC: Do not edit this line. Qbf_parserVisitor.java Version 4.1d1 */
public interface Qbf_parserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTQuant node, Object data);
  public Object visit(ASTOp node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTVarList node, Object data);
}
/* JavaCC - OriginalChecksum=821c0d6d668756056b4377b6f97c75ac (do not edit this line) */
