/* Generated By:JavaCC: Do not edit this line. Qbf_parserTreeConstants.java Version 4.1d1 */
package main.java.logic.parser;

public interface Qbf_parserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTAND = 1;
  public int JJTOR = 2;
  public int JJTNOT = 3;
  public int JJTEXISTS = 4;
  public int JJTFORALL = 5;
  public int JJTVAR = 6;
  public int JJTLOGICAL = 7;


  public String[] jjtNodeName = {
    "void",
    "And",
    "Or",
    "Not",
    "Exists",
    "Forall",
    "Var",
    "Logical",
  };
}
/* JavaCC - OriginalChecksum=5a874bc756590ce24bc821799aa15b57 (do not edit this line) */
